# Generated by Django 5.2.6 on 2025-10-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('rfc_empleado', models.CharField(max_length=13, unique=True)),
                ('puesto_empleado', models.CharField(max_length=100)),
                ('contratacion_empleado', models.DateField()),
            ],
        ),
    ]
